version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1
  circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - circleci-cli/install
      - run:
          name: Process Pre-checks Config
          command: |
            circleci config process .circleci/pre-checks.yml > generated_pre_checks.yml
      - continuation/continue:
          configuration_path: generated_pre_checks.yml

workflows:
  run-environment-selector:
    jobs:
      - setup