version: 2.1

# Enable setup workflow
setup: true

# Define parameters
parameters:
  config-path:
    type: string
    default: ".circleci/pre-checks.yml"

# Use orbs
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.1.0

# Define workflow to generate config
workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: << pipeline.parameters.config-path >>
          mapping: |
            .circleci/.* run-checks-workflow true