version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use appropriate image for Python

jobs:
  prepare_workspace:
    executor: docker-executor
    steps:
      - checkout
      - run: pip install -r requirements.txt  # Install dependencies if any
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit_test:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run: python -m unittest discover  # Run unit tests

  e2e_test:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run: python -m pytest e2e_tests/  # Run end-to-end tests

  sast_scan:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run: pip install bandit  # Example for a security scan tool
      - run: bandit -r .  # Run security scan

  trigger_ephemeral_env:
    executor: docker-executor
    steps:
      - run:
          name: "Trigger Terraform Deployment"
          command: |
            curl -X POST -H "Circle-Token: $CIRCLECI_TOKEN" \
              -d '{ "branch": "main" }' \
              https://circleci.com/api/v2/project/github/your-org/ephemeral-infra/pipeline

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - prepare_workspace
      - unit_test:
          requires:
            - prepare_workspace
      - e2e_test:
          requires:
            - unit_test
      - sast_scan:
          requires:
            - e2e_test
      - trigger_ephemeral_env:
          requires:
            - sast_scan