version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use appropriate image for Python

jobs:
  prepare_workspace:
    executor: docker-executor
    steps:
      - checkout
      - run: pip install -r requirements.txt  # Install dependencies if any
      - persist_to_workspace:
          root: .
          paths:
            - .

  trigger_ephemeral_env:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Trigger Ephemeral Environment Deployment"
          command: |
            echo "Current branch: $CIRCLE_BRANCH"
            curl -X POST -H "Circle-Token: $CIRCLECI_TOKEN" \
              -d '{ "branch": "'"$CIRCLE_BRANCH"'" }' \
              https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - prepare_workspace
      - trigger_ephemeral_env:
          requires:
            - prepare_workspace