version: 2.1

# Enable setup workflow
setup: true

# Define parameters
parameters:
  config-path:
    type: string
    default: ".circleci/pre-checks.yml"

# Use orbs
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.1.0

# Define jobs
jobs:
  run-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Config
          command: echo "Running config job"

  pre-check:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Pre-Check
          command: echo "Running pre-check job"

  pre-main:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Pre-Main
          command: echo "Running pre-main job"

  staging:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Staging
          command: echo "Running staging job"

# Define workflow to generate config
workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: << pipeline.parameters.config-path >>
          mapping: |
            .circleci/config.yml run-config true
            .circleci/pre-checks.yml pre-check true
            .circleci/pre-main.yml pre-main true
            .circleci/staging.yml staging true
      - run-config:
          requires:
            - check-updated-files
      - pre-check:
          requires:
            - run-config
      - pre-main:
          requires:
            - pre-check
      - staging:
          requires:
            - pre-main