version: 2.1

# Enable setup workflow
setup: true

orbs:
  continuation: circleci/continuation@1
  circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - circleci-cli/install
      - run:
          name: Set Environment
          command: |
            chmod u+x .circleci/use_env.sh
            ./.circleci/use_env.sh
            source $BASH_ENV
      - run:
          name: Process Next Config
          command: |
            circleci config process .circleci/pre-checks.yml > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup