version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10  # Use an appropriate Python image

jobs:
  prepare_workspace:
    executor: python-executor
    steps:
      - checkout
      - run: python --version  # Verify Python version
      - persist_to_workspace:
          root: .
          paths:
            - main.py  # Ensure the script is available in other jobs

  unit_test:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run Python Script"
          command: python main.py  # Execute your Python script

  static_analysis:
    executor: python-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run Linting and Security Checks"
          command: |
            pip install flake8 bandit
            flake8 main.py  # Lint check
            bandit -r main.py  # Security scan

  trigger_ephemeral_env:
    executor: python-executor
    steps:
      - run:
          name: "Trigger Terraform Deployment"
          command: |
            curl -X POST -H "Circle-Token: $CIRCLECI_TOKEN" \
              -d '{ "branch": "main" }' \
              https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - prepare_workspace
      - unit_test:
          requires:
            - prepare_workspace
      - static_analysis:
          requires:
            - unit_test
      - trigger_ephemeral_env:
          requires:
            - static_analysis
