# version: 2.1

# executors:
#   python-executor:
#     docker:
#       - image: cimg/python:3.8

# jobs:
#   hold_for_trigger:
#     executor: python-executor
#     steps:
#       - run:
#           name: "Waiting for Manual Approval"
#           command: |
#             echo "Click 'Approve' in CircleCI to trigger the ephemeral environment."

#   trigger_ephemeral:
#     executor: python-executor
#     steps:
#       - checkout
#       - run:
#           name: Trigger Ephemeral Environment
#           command: |
#             if [[ -n "${CIRCLE_PULL_REQUEST}" ]]; then
#               PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
#               echo "Extracted PR Number: ${PR_NUMBER}"

#               JSON_PAYLOAD="{\"branch\": \"fix/show-pr-name-from-backend\", \"parameters\": {\"pr_number\": \"${PR_NUMBER}\", \"pr_branch\": \"${CIRCLE_BRANCH}\"}}"

#               echo "Sending JSON Payload: $JSON_PAYLOAD"

#               RESPONSE=$(curl -s -X POST \
#                 -H "Circle-Token: ${CIRCLECI_TOKEN}" \
#                 -H "Content-Type: application/json" \
#                 -d "$JSON_PAYLOAD" \
#                 "https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline")

#               echo "Response from CircleCI: $RESPONSE"
#             else
#               echo "No PR number found. Skipping ephemeral environment trigger."
#             fi
#       - run:
#           name: Log Message
#           command: |
#             echo "Ephemeral environment for PR #${CIRCLE_BRANCH} is being built. You can check progress in the [CircleCI UI](https://app.circleci.com/pipelines/github/YahyaMohand/ephemeral)."

# workflows:
#   version: 2
#   pr_workflow:
#     jobs:
#       - hold_for_trigger:
#           type: approval
#           filters:
#             branches:
#               ignore: main
#       - trigger_ephemeral:
#           requires:
#             - hold_for_trigger
#           context: aws-creds
#           filters:
#             branches:
#               ignore: main


version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  hold_for_trigger:
    executor: python-executor
    steps:
      - run:
          name: "Waiting for Manual Approval"
          command: |
            echo "Click 'Approve' in CircleCI to trigger the ephemeral environment."

  extract_pr_details:
    executor: python-executor
    steps:
      - run:
          name: "Extract PR Number and Branch"
          command: |
            echo "Extracting PR details..."
            
            if [[ -n "${CIRCLE_PULL_REQUEST}" ]]; then
              PR_NUMBER=$(basename "${CIRCLE_PULL_REQUEST}")
            else
              PR_NUMBER="unknown"
            fi

            echo "PR_NUMBER=${PR_NUMBER}" > /tmp/pr_details.env
            echo "PR_BRANCH=${CIRCLE_BRANCH}" >> /tmp/pr_details.env
      - persist_to_workspace:
          root: /tmp
          paths:
            - pr_details.env

  ephemeral_deployment:
    executor: python-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Load PR Details"
          command: |
            source /tmp/pr_details.env
            echo "PR Number: $PR_NUMBER"
            echo "PR Branch: $PR_BRANCH"

      - trigger:
          project: "YahyaMohnd/ephemeral"
          branch: "main"
          parameters:
            pr_number: "<< pipeline.parameters.pr_number >>"
            pr_branch: "<< pipeline.parameters.pr_branch >>"

workflows:
  version: 2
  pr_workflow:
    jobs:
      - hold_for_trigger:
          type: approval
          filters:
            branches:
              ignore: main
      - extract_pr_details:
          requires:
            - hold_for_trigger
          filters:
            branches:
              ignore: main
      - ephemeral_deployment:
          requires:
            - extract_pr_details
          filters:
            branches:
              ignore: main

