version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  trigger_ephemeral:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Trigger Ephemeral Environment
          command: |
            # Extract PR number from the GitHub URL
            PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
            
            if [ -n "$PR_NUMBER" ]; then
              echo "Triggering ephemeral environment for PR #${PR_NUMBER}"
              
              # Create proper JSON payload
              PAYLOAD=$(cat <<EOF
                {
                  "parameters": {
                    "pr_number": "${PR_NUMBER}",
                    "backend_sha": "${CIRCLE_SHA1}"
                  },
                  "branch": "main"
                }
                EOF
                )
              
              echo "Debug - Payload being sent:"
              echo "$PAYLOAD"
              
              curl -X POST \
                -H "Circle-Token: ${CIRCLECI_TOKEN}" \
                -H "Content-Type: application/json" \
                -d "$PAYLOAD" \
                "https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline"
            else
              echo "No PR number found. Skipping ephemeral environment trigger."
            fi

workflows:
  version: 2
  pr_workflow:
    jobs:
      - trigger_ephemeral:
          context: circleci-api
          filters:
            branches:
              ignore: main