version: 2.1

# Enable setup workflow
setup: true

# Use orbs
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.1.0

# Define jobs
jobs:
  run-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Config
          command: echo "Running config job"

  pre-check:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Pre-Check
          command: echo "Running pre-check job"

  pre-main:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Pre-Main
          command: echo "Running pre-main job"

  staging:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run Staging
          command: echo "Running staging job"

# Define workflow to generate config
workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          mapping: |
            .circleci/config.yml run-config true
      - path-filtering/filter:
          name: check-pre-checks
          base-revision: main
          mapping: |
            .circleci/pre-checks.yml pre-check true
      - path-filtering/filter:
          name: check-pre-main
          base-revision: main
          mapping: |
            .circleci/pre-main.yml pre-main true
      - path-filtering/filter:
          name: check-staging
          base-revision: main
          mapping: |
            .circleci/staging.yml staging true