version: 2.1

jobs:
  trigger_ephemeral:
    executor: docker-executor
    steps:
      - run:
          name: Trigger Ephemeral Environment
          command: |
            PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
            if [ -n "$PR_NUMBER" ]; then
              curl -X POST \
                -H "Circle-Token: ${CIRCLECI_TOKEN}" \
                -H "Content-Type: application/json" \
                -d "{
                  \"branch\": \"main\",
                  \"parameters\": {
                    \"pr_number\": \"${PR_NUMBER}\",
                    \"backend_sha\": \"${CIRCLE_SHA1}\"
                  }
                }" \
                "https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline"
            else
              echo "No PR number found. Skipping ephemeral environment trigger."
            fi

workflows:
  version: 2
  pr_workflow:
    jobs:
      - trigger_ephemeral:
          context:
            - aws-cred