version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  hold_for_trigger:
    executor: python-executor
    steps:
      - run:
          name: "Waiting for Manual Approval"
          command: |
            echo "Click 'Approve' in CircleCI to trigger the ephemeral environment."

  trigger_ephemeral:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Trigger Ephemeral Environment
          command: |
            # Extract PR number from the GitHub URL
            if [[ -n "${CIRCLE_PULL_REQUEST}" ]]; then
              PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
              echo "Extracted PR Number: ${PR_NUMBER}"
              
              # Construct JSON payload
              JSON_PAYLOAD="{\"branch\": \"main\", \"parameters\": {\"pr_number\": \"${PR_NUMBER}\"}}"

              echo "Sending JSON Payload: $JSON_PAYLOAD"

              RESPONSE=$(curl -s -X POST \
                -H "Circle-Token: ${CIRCLECI_TOKEN}" \
                -H "Content-Type: application/json" \
                -d "$JSON_PAYLOAD" \
                "https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline")

              echo "Response from CircleCI: $RESPONSE"

            else
              echo "No PR number found. Skipping ephemeral environment trigger."
            fi
      - run:
          name: Log Message
          command: |
            echo "Ephemeral environment for PR #${PR_NUMBER} is being built. You can check progress in the [CircleCI UI](https://app.circleci.com/pipelines/github/YahyaMohand/ephemeral)."

workflows:
  version: 2
  pr_workflow:
    jobs:
      - hold_for_trigger:
          type: approval
          filters:
            branches:
              ignore: main
      - trigger_ephemeral:
          requires:
            - hold_for_trigger
          context: circleci-api
          filters:
            branches:
              ignore: main
