version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  trigger_ephemeral:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Trigger Ephemeral Environment
          command: |
            # Extract PR number from the GitHub URL
            if [[ -n "${CIRCLE_PULL_REQUEST}" ]]; then
              PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
              echo "Extracted PR Number: ${PR_NUMBER}"
              
              JSON_PAYLOAD=$(echo '{
                "branch": "main",
                "parameters": {
                  "pipeline-parameter": {
                    "pr_number": "'"${PR_NUMBER}"'",
                    "backend_sha": "'"${CIRCLE_SHA1}"'"
                  }
                }
              }')

              echo "JSON Payload: $JSON_PAYLOAD"

              curl -X POST \
                -H "Circle-Token: ${CIRCLECI_TOKEN}" \
                -H "Content-Type: application/json" \
                -d "$JSON_PAYLOAD" \
                "https://circleci.com/api/v2/project/github/YahyaMohand/ephemeral/pipeline"
            else
              echo "No PR number found. Skipping ephemeral environment trigger."
            fi

workflows:
  version: 2
  pr_workflow:
    jobs:
      - trigger_ephemeral:
          context: circleci-api
          filters:
            branches:
              ignore: main
