version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  pre-check:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Say Hello Before Staging
          command: echo "Hello World! Pre-check before merging to main."

workflows:
  pre-check-before-merging:
    jobs:
      - pre-check
      - hold-for-approval:
          type: approval
          requires:
            - pre-check
