version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  circleci-cli: circleci/circleci-cli@0.1.9

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python main.py
      - circleci-cli/install
      - run:
          name: Process Pre-main Config
          command: |
            circleci config process .circleci/pre-main.yml > generated_pre_main.yml
      - continuation/continue:
          configuration_path: generated_pre_main.yml

workflows:
  test-pipeline:
    jobs:
      - test