version: 2.1

orbs:
  continuation: circleci/continuation@1.1.0
  circleci-cli: circleci/circleci-cli@0.1.9

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  pre-check:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Say Hello Before Staging
          command: echo "Hello World! Pre-check before merging to main."
      - circleci-cli/install
      - run:
          name: Process Staging Config
          command: |
            circleci config process .circleci/staging.yml > generated_staging.yml
      - continuation/continue:
          configuration_path: generated_staging.yml

  manual-approval:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Await Manual Approval
          command: echo "Please approve this step in CircleCI UI to proceed to staging."

workflows:
  pre-check-before-merging:
    jobs:
      - pre-check
      - manual-approval:
          requires:
            - pre-check
      - hold-for-approval:
          type: approval
          requires:
            - manual-approval