version: 2.1

orbs:
  continuation: circleci/continuation@1.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python main.py
      - run:
          name: Process Next Config
          command: |
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              circleci config process .circleci/pre-main.yml > processed_next_config.yml
              cat processed_next_config.yml
              - continuation/continue:
                  configuration_path: processed_next_config.yml
            fi

workflows:
  test-pipeline:
    jobs:
      - test